### ISSUE TITLE
activation of daily summary not possible

### ISSUE THREAD

**Issue by EtienneBerlin** [thoka/discourse-mail-daily-summary#1]
when activating the daily summary in user settings - the setting is not taken. after logging out and back in - it is NOT activated. 

activate setting to get daily summary:

<img width="606" alt="20230813-00h01m40s-CleanShot-Safari-E-Mails - Einstellungen - Etienne - Fachforum Kinderversorgungsnetz Berlin" src="https://github.com/thoka/discourse-mail-daily-summary/assets/39301600/d53f0662-abad-497f-84fb-533362d1c879">

after logging out and back in again it looks like this:

<img width="563" alt="20230813-00h02m05s-CleanShot-Safari-E-Mails - Einstellungen - Etienne - Fachforum Kinderversorgungsnetz Berlin" src="https://github.com/thoka/discourse-mail-daily-summary/assets/39301600/1387aa34-af6f-4b6d-838c-ccf21c05754c">

**Comment by thoka** [comment]
Confirmed.

Although: the changes are written to the database, but not shown in the UI. 
It is sufficient to reload the page to reproduce the error.

**Comment by thoka** [comment]
should be fixed by e72488a
